version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      
      # Install docker compose
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -o docker-compose
            chmod +x docker-compose
            sudo mv docker-compose /usr/local/bin/

      # Build and run tests using docker-compose
      - run:
          name: Run tests
          command: |
            docker-compose build test
            docker-compose run --rm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
