version: 2.1

jobs:
  test:
    docker:
      - image: cimg/rust:1.75.0
    steps:
      - checkout
      - setup_remote_docker:
          version: default

      # Install docker compose
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -o docker-compose
            chmod +x docker-compose
            sudo mv docker-compose /usr/local/bin/

      # Start Redis using docker-compose
      - run:
          name: Start Redis
          command: docker-compose up -d redis

      # Wait for Redis to be ready
      - run:
          name: Wait for Redis
          command: |
            timeout 20s bash -c '
            until docker-compose exec -T redis redis-cli ping; do
              echo "Waiting for Redis..."
              sleep 1
            done'

      # Cache dependencies
      - restore_cache:
          key: cargo-cache-{{ checksum "Cargo.lock" }}

      # Build and run tests
      - run:
          name: Run tests
          command: cargo test -- --test-threads=1

      # Save cache
      - save_cache:
          key: cargo-cache-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo
            - target

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
