version: 2.1

jobs:
  code-quality:
    docker:
      - image: cimg/rust:1.86.0
    steps:
      - checkout
      - run:
          name: Install rustfmt and clippy
          command: |
            rustup component add rustfmt
            rustup component add clippy
      - run:
          name: Check formatting
          command: cargo fmt -- --check
      - run:
          name: Run clippy
          command: cargo clippy -- -D warnings

  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64 -o docker-compose
            chmod +x docker-compose
            sudo mv docker-compose /usr/local/bin/
      - run:
          name: Run tests
          command: |
            docker-compose build test
            docker-compose run --rm test

  publish:
    docker:
      - image: cimg/rust:1.86.0
    steps:
      - checkout
      - run:
          name: Install cargo-audit
          command: cargo install cargo-audit
      - run:
          name: Check dependencies for security vulnerabilities
          command: cargo audit
      - run:
          name: Verify package version
          command: |
            CURRENT_VERSION=$(grep -oP 'version = "\K[^"]+' Cargo.toml)
            echo "Current version: ${CURRENT_VERSION}"
            
            # Use cargo search with proper error handling
            SEARCH_RESULT=$(cargo search queue_workers --limit 1 || echo "Package not found")
            if echo "$SEARCH_RESULT" | grep -q "Package not found"; then
              echo "Package not found in registry - this must be the first publication"
            else
              PUBLISHED_VERSION=$(echo "$SEARCH_RESULT" | grep -oP 'queue_workers = "\K[^"]+' || echo "not found")
              echo "Latest published version: ${PUBLISHED_VERSION}"
              
              if [ "$PUBLISHED_VERSION" = "$CURRENT_VERSION" ]; then
                echo "Error: Version ${CURRENT_VERSION} is already published"
                exit 1
              fi
              
              if [ "$PUBLISHED_VERSION" = "not found" ]; then
                echo "Error: Failed to parse version from cargo search output"
                echo "Search result was: $SEARCH_RESULT"
                exit 1
              fi
            fi
      - run:
          name: Build documentation
          command: cargo doc --no-deps
      - run:
          name: Verify package
          command: |
            cargo package
            cargo package --list
      - run:
          name: Publish to crates.io
          command: |
            echo "Publishing version $(grep -oP 'version = "\K[^"]+' Cargo.toml)"
            cargo publish --token ${CRATES_IO_TOKEN}
      - run:
          name: Create git tag
          command: |
            VERSION=v$(grep -oP 'version = "\K[^"]+' Cargo.toml)
            git tag -a ${VERSION} -m "Release ${VERSION}"
            git push origin ${VERSION}

workflows:
  version: 2
  build_test_publish:
    jobs:
      - code-quality
      - test:
          requires:
            - code-quality
      - publish:
          context: crates-io-publish-context
          requires:
            - test
          # filters:
          #   branches:
          #     only: master
